### ISSUE TITLE
libbitcoin on iOS?

### ISSUE THREAD

**Issue by rhabal** [libbitcoin/libbitcoin#243]
Is it possible to compile / link libbitcoin on iOS?

**Comment by evoskuil** [comment]
We don't have CI platforms for testing this, but I believe @swansontec has some experience with it.

**Comment by swansontec** [comment]
Yep! Our app, [Airbitz](airbitz.co), uses libbitcoin on iOS. Take a look in our [deps](https://github.com/Airbitz/airbitz-core/tree/master/deps) folder to see our build system. This thing downloads all our dependent libraries (boost, openssl, secp256k1, libbitcoin, etc.), compiles them for iOS (or Android), and bundles them up for our app to use. Each package has its own recipe in the "recipes" folder, which provides instructions on what to download and how to build it.

Then, in our iOS project, we have a (simple shell script)[https://github.com/Airbitz/airbitz-ios-gui/blob/master/mkabc] that knows how to copy over the build results from our core. The iOS platform is pretty nice, since you have ObjectiveC++, which can talk to libbitcoin. This is much better than Android, where you have to wrap everything in a layer of JNI.

Hopefully this gets you on the right track. One word of warning - the version of libbitcoin we are using is somewhat out-of-date, since we've just been back-porting fixes to our own branch. You will probably want to update the recipe to download a later version.

**Comment by rhabal** [comment]
thanks - will check it out
