### ISSUE TITLE
Make error: makefile:2744: recipe for target 'src/chain/src_libbitcoin_la-block.lo' failed

### ISSUE THREAD

**Issue by anon54** [libbitcoin/libbitcoin#461]
On Fedora 23, after running sudo ./install.sh, during the make of libbitcoin, I get this error:

  CXX      src/src_libbitcoin_la-constants.lo
  CXX      src/src_libbitcoin_la-error.lo
  CXX      src/chain/src_libbitcoin_la-block.lo
  CXX      src/chain/src_libbitcoin_la-header.lo
  CXX      src/chain/src_libbitcoin_la-input.lo
  CXX      src/chain/src_libbitcoin_la-output.lo
  CXX      src/chain/src_libbitcoin_la-point.lo
  CXX      src/chain/src_libbitcoin_la-point_iterator.lo
  CXX      src/chain/src_libbitcoin_la-transaction.lo
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Makefile:2744: recipe for target 'src/chain/src_libbitcoin_la-block.lo' failed
make: *** [src/chain/src_libbitcoin_la-block.lo] Error 1
make: *** Waiting for unfinished jobs....

How can I find out more information to resolve this?

Thanks.

**Comment by thecodefactory** [comment]
How much memory does the machine have?  I've most often seen errors like this when the machine has exhausted resources during a C++ compile.

**Comment by anon54** [comment]
I'll make sure it has at least a gig of ram available and report back.

**Comment by thecodefactory** [comment]
Ok.  If you're just building libbitcoin, you may be ok building with 1GB RAM.  If you were running the install.sh for something like libbitcoin_explorer, I've seen it run out of memory while building the tests with 4GB RAM (but was ok if tests were disabled).  Haven't looked into much since upgrading, but building on low memory machines isn't a design goal that I'm aware of.
