### ISSUE TITLE
[master] test failures due to tx inputs/outputs not propagated.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#516]
https://github.com/libbitcoin/libbitcoin/blob/master/src/message/transaction_message.cpp#L84-L96

@k-ballo do you have any other information, I'm not seeing failures on gcc/clan/osx/msvc:

https://travis-ci.org/libbitcoin/libbitcoin/builds/162996023

Note that master is moving quite rapidly presently.

**Comment by K-ballo** [comment]
> @k-ballo do you have any other information,

Sure, those two delegating constructors are attempting to initialize `inputs` and `outputs` from themselves, rather than using `other.inputs` and `other.outputs`.

While on the subject, why is `std::forward<chain::input::list>` needed here instead of the usual `std::move`?

> I'm not seeing failures on gcc/clan/osx/msvc:
> 
> https://travis-ci.org/libbitcoin/libbitcoin/builds/162996023

I'll have to assume your tests do not cover that code path (I'm not sure how to extract that information from coveralls). I've just tried running _transaction_message_tests_ and I only see failures on msvc (*), which is not included in the link above. If I had to guess I would say the other compilers are eliding that particular move constructor.

(*) I had to disable `libbitcoin::resource_lock` for libbitcoin to build with msvc, `boost::interprocess::file_lock` is not compatible with `boost::filesystem::path` v3, but this should have no effect on `transaction_message` whatsoever.

**Comment by evoskuil** [comment]
resource_lock is dead code and has been removed. A PR has been issued that fixes the two transaction_message move cons. Thanks for reporting!

Incidentally boost::interprocess::file_lock is used in libbitcoin-database and has no problem constructing with a boost::filesystem::path on any of our supported platforms (incl msvc with boost 1.56.0).

**Comment by evoskuil** [comment]
std::forward<> is used in place of std::move in the case of template arguments, allowing both move and copy parameterization in that case. Otherwise there should be no difference and these cases could use std::move instead. However I believe we ran into some issue in making that change, still looking into it.
