### ISSUE TITLE
Cannot Build in VS2015

### ISSUE THREAD

**Issue by mayaomichael** [libbitcoin/libbitcoin#964]
Cannot build under vs2015 using the latest version. Got following error:
2>..\..\..\..\src\math\elliptic_curve.cpp(179): error C3861: 'secp256k1_ec_privkey_negate': identifier not found [C:\libcoin_all\libbitcoin\builds\msvc\vs2015\libbitcoin\libbitcoin.vcxproj]

Could someone advise how to resolve?

**Comment by evoskuil** [comment]
I recommend building the release branch, version3.

**Comment by evoskuil** [comment]
This is the consequence of name conflicts due to [another NuGet user publishing the output of our packages](https://www.nuget.org/profiles/kobake) and then failing to maintain them or respond to requests to remove them. This has created naming inconsistencies for both zeromq and secp256k1. Those inconsistencies were inadvertently removed in our metadata at some point, affecting the libbitcoin VS2015 build (only).

**Comment by evoskuil** [comment]
It appears that the problem will also exist in version3. I'm pushing up a fix now.

**Comment by evoskuil** [comment]
Resolved in master and version3, thanks @mayaomichael for reporting!

**Comment by mayaomichael** [comment]
Thanks @evoskuil for the quick fix!
